const { test } = require('node:test');
const assert = require('node:assert/strict');
const { readFileSync, existsSync } = require('node:fs');
const { resolve } = require('node:path');

const rulesDir = resolve(__dirname, '../../rules');
const commandsDir = resolve(__dirname, '../../commands');

// --- Helpers ---

/** Parse ## headings from markdown, skipping fenced code blocks */
function extractHeadings(content) {
  const lines = content.split('\n');
  const headings = [];
  let inFence = false;
  for (const line of lines) {
    if (line.trim().startsWith('```')) {
      inFence = !inFence;
      continue;
    }
    if (!inFence && /^## /.test(line)) {
      headings.push(line.replace(/^## /, '').trim());
    }
  }
  return headings;
}

/** Classify sections: active, commented, missing, custom */
function classifySections(baseHeadings, overrideContent) {
  const lines = overrideContent.split('\n');
  const activeHeadings = extractHeadings(overrideContent);
  const commentedHeadings = [];
  for (const line of lines) {
    const match = line.match(/^<!--\s*##\s+(.+?)(?:\s*-->|\s*$)/);
    if (match) commentedHeadings.push(match[1].trim());
  }

  const result = [];
  for (const h of baseHeadings) {
    if (activeHeadings.includes(h)) {
      result.push({ heading: h, status: 'active', source: 'base' });
    } else if (commentedHeadings.includes(h)) {
      result.push({ heading: h, status: 'commented', source: 'base' });
    } else {
      result.push({ heading: h, status: 'missing', source: 'base' });
    }
  }
  for (const h of activeHeadings) {
    if (!baseHeadings.includes(h)) {
      result.push({ heading: h, status: 'custom', source: 'custom' });
    }
  }
  return result;
}

/** Detect active content using comment-state-aware sentinel parser */
function hasActiveContent(content) {
  const lines = content.split('\n');
  let inComment = false;
  for (const line of lines) {
    const stripped = line.trim();
    if (stripped.includes('<!--') && stripped.includes('-->')) {
      continue; // single-line comment
    }
    if (stripped.includes('<!--') && !stripped.includes('-->')) {
      inComment = true;
      continue;
    }
    if (inComment) {
      if (stripped.includes('-->')) inComment = false;
      continue;
    }
    if (stripped.startsWith('#')) continue;
    if (stripped === '') continue;
    return true;
  }
  return false;
}

/** Validate custom heading input */
function validateHeading(text) {
  if (text.length < 3 || text.length > 80) return 'Heading too short/long';
  if (!/^[a-zA-Z0-9 ()\-]+$/.test(text)) return 'Heading contains invalid characters';
  return null;
}

/** Parse Based-on hash from override file */
function parseBasedOnHash(content) {
  const match = content.match(/<!-- Based on: .+? @ ([0-9a-f]{7,40})/);
  return match ? match[1] : null;
}

// --- Tests ---

test('install-rules.md has v2 customize sub-flags in argument-hint', () => {
  const content = readFileSync(resolve(commandsDir, 'install-rules.md'), 'utf8');
  assert.match(content, /--add-section/, 'argument-hint should contain --add-section');
  assert.match(content, /--update-section/, 'argument-hint should contain --update-section');
  assert.match(content, /--reset/, 'argument-hint should contain --reset');
});

test('install-rules.md has sub-flag mutual exclusion matrix', () => {
  const content = readFileSync(resolve(commandsDir, 'install-rules.md'), 'utf8');
  assert.match(content, /mutually exclusive/, 'should document mutual exclusion');
  assert.match(content, /Error:.*mutually exclusive/, 'should have error message for mutual exclusion');
});

test('install-rules.md has four customize modes', () => {
  const content = readFileSync(resolve(commandsDir, 'install-rules.md'), 'utf8');
  assert.match(content, /Status Mode/, 'should have Status Mode');
  assert.match(content, /Add Section Mode/, 'should have Add Section Mode');
  assert.match(content, /Update Section Mode/, 'should have Update Section Mode');
  assert.match(content, /Reset Mode/, 'should have Reset Mode');
});

test('install-rules.md has sentinel-based content detection', () => {
  const content = readFileSync(resolve(commandsDir, 'install-rules.md'), 'utf8');
  assert.match(content, /in_comment/, 'should have comment-state-aware detection logic');
  assert.match(content, /has_active_content/, 'should track active content state');
});

test('auto-loop-project.md template has Generated-by sentinel', () => {
  const content = readFileSync(resolve(rulesDir, 'auto-loop-project.md'), 'utf8');
  assert.match(content, /<!-- Generated by: \/install-rules -->/, 'template should have sentinel');
});

test('auto-loop-project.md template has Based-on hash', () => {
  const content = readFileSync(resolve(rulesDir, 'auto-loop-project.md'), 'utf8');
  const hash = parseBasedOnHash(content);
  assert.ok(hash, 'template should have Based-on hash');
  assert.match(hash, /^[0-9a-f]{7,}$/, 'hash should be hex string');
});

test('extractHeadings parses ## headings correctly', () => {
  const md = '# Title\n## Section One\ntext\n## Section Two\nmore text';
  const headings = extractHeadings(md);
  assert.deepEqual(headings, ['Section One', 'Section Two']);
});

test('extractHeadings skips ## inside fenced code blocks', () => {
  const md = '## Real\n```\n## Fake Inside Code\n```\n## Also Real';
  const headings = extractHeadings(md);
  assert.deepEqual(headings, ['Real', 'Also Real']);
});

test('classifySections identifies active, commented, missing, custom', () => {
  const baseHeadings = ['Auto-Trigger', 'Exit Conditions', 'P2/Nit Quality Sweep'];
  const override = [
    '# Auto-Loop Project Overrides',
    '## Auto-Trigger',
    'custom content',
    '<!-- ## Exit Conditions',
    'stuff',
    '-->',
    '## My Custom Rule',
    'content',
  ].join('\n');

  const result = classifySections(baseHeadings, override);
  assert.equal(result.length, 4);
  assert.equal(result[0].status, 'active');    // Auto-Trigger
  assert.equal(result[1].status, 'commented'); // Exit Conditions
  assert.equal(result[2].status, 'missing');   // P2/Nit Quality Sweep
  assert.equal(result[3].status, 'custom');    // My Custom Rule
});

test('hasActiveContent returns false for template-only file', () => {
  const template = readFileSync(resolve(rulesDir, 'auto-loop-project.md'), 'utf8');
  assert.equal(hasActiveContent(template), false, 'template should have no active content');
});

test('hasActiveContent returns true when section is uncommented', () => {
  const content = [
    '# Title',
    '<!-- Based on: auto-loop.md @ abc1234 -->',
    '<!-- Generated by: /install-rules -->',
    '',
    '## Auto-Trigger',
    '',
    '| Change Type | Event |',
  ].join('\n');
  assert.equal(hasActiveContent(content), true);
});

test('hasActiveContent handles multiline comments correctly', () => {
  const content = [
    '# Title',
    '<!-- Precedence: this file wins -->',
    '<!--',
    'This is a multiline comment',
    'spanning several lines',
    '-->',
    '',
    '<!-- ## Commented Section',
    'content here',
    '-->',
  ].join('\n');
  assert.equal(hasActiveContent(content), false, 'all-commented file should return false');
});

test('validateHeading rejects too short', () => {
  assert.ok(validateHeading('AB'), 'should reject 2-char heading');
});

test('validateHeading rejects too long', () => {
  assert.ok(validateHeading('A'.repeat(81)), 'should reject 81-char heading');
});

test('validateHeading rejects invalid characters', () => {
  assert.ok(validateHeading('Has <!-- comment -->'), 'should reject comment delimiters');
});

test('validateHeading accepts valid heading', () => {
  assert.equal(validateHeading('My Integration Tests'), null);
  assert.equal(validateHeading('Exit Conditions (Only)'), null);
  assert.equal(validateHeading('P2-Nit Quality Sweep'), null);
});

test('parseBasedOnHash extracts 7-char blob hash', () => {
  const content = '<!-- Based on: auto-loop.md @ a17d1b3 (2026-03-13) -->';
  assert.equal(parseBasedOnHash(content), 'a17d1b3');
});

test('parseBasedOnHash extracts full 40-char hash', () => {
  const content = '<!-- Based on: auto-loop.md @ a17d1b3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c (2026-03-13) -->';
  assert.equal(parseBasedOnHash(content), 'a17d1b3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c');
});

test('parseBasedOnHash returns null for missing hash', () => {
  assert.equal(parseBasedOnHash('no hash here'), null);
});

test('duplicate heading detection finds duplicates', () => {
  const content = '## Auto-Trigger\nstuff\n## Exit Conditions\nmore\n## Auto-Trigger\nduplicate';
  const headings = extractHeadings(content);
  const seen = new Set();
  const dupes = [];
  for (const h of headings) {
    if (seen.has(h)) dupes.push(h);
    seen.add(h);
  }
  assert.deepEqual(dupes, ['Auto-Trigger'], 'should detect duplicate heading');
});

test('examples section has all four customize modes', () => {
  const content = readFileSync(resolve(commandsDir, 'install-rules.md'), 'utf8');
  assert.match(content, /--customize auto-loop\n/, 'should have status mode example');
  assert.match(content, /--customize auto-loop --add-section/, 'should have add-section example');
  assert.match(content, /--customize auto-loop --update-section/, 'should have update-section example');
  assert.match(content, /--customize auto-loop --reset/, 'should have reset example');
});
